### ISSUE TITLE
payload progress bar

### ISSUE THREAD

**Issue by miyho** [delegacz/delihudneue#1]
so, i really like this hud and i started using since some time, and ive noticed that the payload wont show if theres people pushing / how many people are pushing and this is really bad as i play demoman on highlander. I really like this hud and i dont want to change again so could you please add the people pushing counter on the payload mode? id really aprecciate it so i can use this hud

**Comment by Stattek** [comment]
Added in PR #2!

**Comment by miyho** [comment]
ok

Em dom., 13 de out. de 2024 às 09:15, Mateusz Delegacz <
***@***.***> escreveu:
